on:
  push:
    branches:
      - main
      - master

name: blogdown

jobs:
  build:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        uses: r-lib/actions/setup-r@v1

      - name: Install pandoc
        run: |
          brew install pandoc
      - name: Install blogdown
        run: |
          R -e 'install.packages("blogdown")'
      - name: Install hugo
        run: |
          R -e 'blogdown::install_hugo(version = "0.60.1")'
      - name: Build site
        run: |
          R -e 'blogdown::build_site(local = TRUE, build_rmd = TRUE)'
      - uses: actions/upload-artifact@v1
        with:
          name: public
          path: public
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
